name = "Kami Chan Optimized"
author = "mja00"
version = "2.1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c3ddbca5e4aa73f5f6aeb0735cdb57fef70c5ae48a97622b84fd36a193525d6"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"

[options]
acceptable-game-versions = ["1.19.4"]
