name = "Kami Chan Optimized"
author = "mja00"
version = "4.1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c98e67b5040c5eda7618c5cbd6253add0b467222c15c9552641623c004eef2c1"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
