name = "Kami Chan Optimized"
author = "mja00"
version = "2.1.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d285ad4d4322a0d11fa26fb32659977aa7c324eb84ef241e95f8a235700c588"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"

[options]
acceptable-game-versions = ["1.19.4"]
